# Generated by Django 5.2.8 on 2025-12-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_capacity_course_course_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=20, verbose_name='Day of Week')),
                ('start_time', models.TimeField(verbose_name='start')),
                ('end_time', models.TimeField(verbose_name='finish')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.AddField(
            model_name='course',
            name='time_slots',
            field=models.ManyToManyField(to='courses.timeslot'),
        ),
    ]
